{
 "title": "SonarQube",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "projectName",
    "label": "Project Name",
    "query": {
     "query": "label_values(sonarqube_bugs, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alert Status",
   "type": "table",
   "description": "The project status with regard to its quality gate.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sonarqube_alert_status{name=~\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Quality Gates Details",
   "type": "table",
   "description": "The project detailed status with regard to its quality gate",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sonarqube_quality_gate_details{name=~\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Non Commenting Lines of Code Distributed By Language",
   "type": "table",
   "description": "Non Commenting Lines of Code Distributed By Language",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sonarqube_ncloc_language_distribution{name=~\"$projectName\"}) by (language)",
     "legendFormat": "{{language}}"
    }
   ]
  },
  {
   "title": "Major Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_major_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Lines to Cover",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_lines_to_cover{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(sonarqube_coverage{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Execution duration of unit tests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_test_execution_time{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bugs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_bugs{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_vulnerabilities{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_code_smells{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "stat",
   "description": "Total effort (in hours) to fix all the issues on the component and therefore to comply to all the requirements.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_sqale_index{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Minor Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_minor_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Functions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_functions{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Condition Coverage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(sonarqube_branch_coverage{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Density of successful unit tests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_test_success_density{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of unit test errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_test_errors{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of comment lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_comment_lines{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Security hotspots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_security_hotspots{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Comment Lines Density",
   "type": "stat",
   "description": "Comments balanced by ncloc + comment lines",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_comment_lines_density{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reliability Remediation Effort",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_reliability_remediation_effort{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reopened Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_reopened_issues{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of generated lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_generated_lines{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Duplicated lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_duplicated_lines{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sqale Debt Ratio",
   "type": "stat",
   "description": "Ratio of the actual technical debt compared to the estimated cost to develop the whole source code from scratch",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_sqale_debt_ratio{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reliability rating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_reliability_rating{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Duplicated lines density",
   "type": "stat",
   "description": "Duplicated lines balanced by statements",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_duplicated_lines_density{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Conditions to cover",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_conditions_to_cover{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Security Review To Review Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_security_hotspots_to_review_status{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Duplicated files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_duplicated_files{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Security Rating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(sonarqube_security_rating{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Critical issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_critical_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Line Coverage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(sonarqube_line_coverage{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cognitive complexity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_cognitive_complexity{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Duplicated Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_duplicated_blocks{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Security Review Rating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(sonarqube_security_review_rating{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "stat",
   "description": "Coverage by tests",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_coverage{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_files{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Generated non Commenting Lines of Code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_generated_ncloc{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Blocker issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_blocker_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of unit test failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_test_failures{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sqale Rating",
   "type": "stat",
   "description": "A-to-E rating based on the technical debt ratio",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(sonarqube_sqale_rating{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Security Review Reviewed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_security_hotspots_reviewed_status{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Open issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_open_issues{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Security remediation effort",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_security_remediation_effort{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of projects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_projects{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Skipped tests",
   "type": "stat",
   "description": "Number of skipped unit tests",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_skipped_tests{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Effort to reach maintainability rating A",
   "type": "stat",
   "description": "Effort to reach maintainability rating A",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_effort_to_reach_maintainability_rating_a{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_code_smells{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Percentage of Security Hotspots Reviewed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(sonarqube_security_hotspots_reviewed{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of statements",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_statements{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Info issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_info_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Non commenting lines of code",
   "type": "stat",
   "description": "Non commenting lines of code",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_ncloc{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Quality gate details",
   "type": "stat",
   "description": "The project detailed status with regard to its quality gate",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_quality_gate_details{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Confirmed issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_confirmed_issues{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_classes{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uncovered lines",
   "type": "stat",
   "description": "Coverage by tests",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_uncovered_lines{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Won't fix issues",
   "type": "stat",
   "description": "Won't fix issues",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_wont_fix_issues{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "False positive issues",
   "type": "stat",
   "description": "False positive issues",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_false_positive_issues{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Development cost",
   "type": "stat",
   "description": "Development cost",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_development_cost{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Coverage of new/changed code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_coverage{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cyclomatic complexity",
   "type": "stat",
   "description": "Cyclomatic complexity",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_complexity{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_lines{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tests",
   "type": "stat",
   "description": "Number of unit tests",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_tests{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uncovered conditions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_uncovered_conditions{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "General New Code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true
  },
  {
   "title": "New Blocker issues",
   "type": "stat",
   "description": "New Blocker issues",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_blocker_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Security Review To Review Status on New Code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_security_hotspots_to_review_status{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Condition coverage of new/changed code",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(sonarqube_new_branch_coverage{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New Major Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_major_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_lines{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Security Review Reviewed Status on New Code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_security_hotspots_reviewed_status{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_vulnerabilities{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uncovered lines on new code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_uncovered_lines{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New Security Hotspots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_security_hotspots{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uncovered conditions on new code",
   "type": "stat",
   "description": "Uncovered conditions on new code",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_uncovered_conditions{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Lines to cover on new code",
   "type": "stat",
   "description": "Lines to cover on new code",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_lines_to_cover{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Lines duplicated lines",
   "type": "stat",
   "description": "Duplicated Lines on New Code",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_duplicated_lines{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New Code Smells",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_code_smells{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New bugs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_bugs{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New Sqale Debt Ratio",
   "type": "stat",
   "description": "Technical Debt Ratio of new/changed code.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_sqale_debt_ratio{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New technical debt",
   "type": "stat",
   "description": "Added technical debt",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_technical_debt{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Duplicated lines (%) on new code balanced by statements",
   "type": "stat",
   "description": "Duplicated lines (%) on new code balanced by statements",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_duplicated_lines_density{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Security rating on new code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(sonarqube_new_security_rating{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New security remediation effort",
   "type": "stat",
   "description": "Security remediation effort on new code",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_security_remediation_effort{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Line coverage of added/changed code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_line_coverage{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New Reliability remediation effort",
   "type": "stat",
   "description": "Reliability remediation effort on new code",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_reliability_remediation_effort{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Conditions to cover on new code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_conditions_to_cover{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Development cost on new code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_development_cost{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New Blocker issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_blocker_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New issues",
   "type": "stat",
   "description": "New issues",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Maintainability rating on new code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_maintainability_rating{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Security Review Rating on New Code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_security_review_rating{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Duplicated blocks on new code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_duplicated_blocks{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New Info issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_info_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New Minor issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_minor_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Percentage of Security Hotspots Reviewed on New Code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_security_hotspots_reviewed{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New Critical issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_critical_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reliability rating on new code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_reliability_rating{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bugs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sonarqube_bugs{name=~\"$projectName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Vulnerabilities",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "sonarqube_vulnerabilities{name=~\"$projectName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Code Smells",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sonarqube_code_smells{name=~\"$projectName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Technical Debt",
     "type": "timeseries",
     "description": "Total effort (in hours) to fix all the issues on the component and therefore to comply to all the requirements.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sonarqube_sqale_index{name=~\"$projectName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Coverage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sonarqube_coverage{name=~\"$projectName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Major Issues",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sonarqube_major_violations{name=~\"$projectName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Development cost",
     "type": "timeseries",
     "description": "Development cost",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sonarqube_development_cost{name=~\"$projectName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Graphs New Code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "New Blocker issues",
     "type": "timeseries",
     "description": "New Blocker issues",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "sonarqube_new_blocker_violations{name=~\"$projectName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Security Review Reviewed Status on New Code",
     "type": "timeseries",
     "description": "Security Review Reviewed Status on New Code",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "targets": [
      {
       "expr": "sonarqube_new_security_hotspots_reviewed_status{name=~\"$projectName\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}