{
 "title": "SonarQube",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "projectName",
    "label": "Project Name",
    "query": {
     "query": "label_values(sonarqube_bugs, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bugs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_bugs{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_vulnerabilities{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_code_smells{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_sqale_index{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sonarqube_coverage{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "General New Code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "New Blocker issues",
   "type": "stat",
   "description": "New Blocker issues",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_blocker_violations{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Security Review Reviewed Status on New Code",
   "type": "stat",
   "description": "Security Review Reviewed Status on New Code",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sonarqube_new_security_hotspots_reviewed_status{name=~\"$projectName\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Bugs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sonarqube_bugs{name=~\"$projectName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=~\"$projectName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=~\"$projectName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=~\"$projectName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sonarqube_coverage{name=~\"$projectName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Graphs New Code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true
  },
  {
   "title": "New Blocker issues",
   "type": "timeseries",
   "description": "New Blocker issues",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sonarqube_new_blocker_violations{name=~\"$projectName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Security Review Reviewed Status on New Code",
   "type": "timeseries",
   "description": "Security Review Reviewed Status on New Code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sonarqube_new_security_hotspots_reviewed_status{name=~\"$projectName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}